#!/usr/bin/env python

SIG_TYPE_MIN = 65
SIG_TYPE_MAX = 73

START_COMMAND = SIG_TYPE_MAX
CAN_PASS_COMMAND = SIG_TYPE_MAX -1

CAN_CLIP_PT_A = SIG_TYPE_MIN
CAN_CLIP_PT_B = SIG_TYPE_MIN + 1
CAN_CLIP_PT_C = SIG_TYPE_MIN + 2
CAN_CLIP_PT_D = SIG_TYPE_MIN + 3
CAN_CLIP_PT_E = SIG_TYPE_MIN + 4